In [12]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import time

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB



# Importing dataset

data = pd.read_csv("C:\\Users\\HP\\Desktop\\IRIS.csv")


# Convert categorical variable to numeric



# Cleaning dataset of NaN
data["species"]=np.where(data["species"]=="Iris-setosa",0,

                                  np.where(data["species"]=="Iris-versicolor",1,

                                           np.where(data["species"]=="Iris-virginica",2,3)

                                          )

                                 )


X_train, X_test = train_test_split(data, test_size=0.5, random_state=int(time.time()))


gnb = GaussianNB()

used_features =[

    "sepal_length",

    "sepal_width",

    "petal_length",

    "petal_width",

]



# Train classifier

y_p=gnb.fit(

    X_train[used_features].values,

    X_train["species"]

)

y_pred = gnb.predict(X_test[used_features])




# Print results

print("Number of mislabeled points out of a total {} points : {}, performance {:05.2f}%"

      .format(

          X_test.shape[0],

          (X_test["species"] != y_pred).sum(),

          100*(1-(X_test["species"] != y_pred).sum()/X_test.shape[0])

))


from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix( X_train["species"],y_pred))

Number of mislabeled points out of a total 75 points : 4, performance 94.67%
[[ 7  8  8]
 [ 9  8  8]
 [11  7  9]]


In [14]:


print(classification_report(X_train["species"],y_pred))



             precision    recall  f1-score   support

          0       0.26      0.30      0.28        23
          1       0.35      0.32      0.33        25
          2       0.36      0.33      0.35        27

avg / total       0.33      0.32      0.32        75

