In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline
dataset=pd.read_csv('/Users/anirudh/Desktop/Iris.csv')
dataset.Species.replace(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], [1, 2, 3], inplace=True)
y = dataset.Species.values
x = dataset.drop(['Species'],axis=1).values

In [2]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)  
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(x_train, y_train)  
ypredict = svclassifier.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,ypredict))  

[[ 8  0  0]
 [ 0 14  0]
 [ 0  0 16]]
