In [25]:
import keras
import pandas as pd  
import seaborn as sns
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd 
from sklearn.preprocessing import normalize 

In [26]:
data=pd.read_csv("Iris.csv")
print("Describing the data: ",data.describe())
print("Info of the data:",data.info())

Describing the data:                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Sp

In [27]:
print("10 first samples of the dataset:",data.head(10))
print("10 last samples of the dataset:",data.tail(10))

10 first samples of the dataset:    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa
10 last samples of the dataset:       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141          

In [28]:
print(data["Species"].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [29]:
data.loc[data["Species"]=="Iris-setosa","Species"]=0
data.loc[data["Species"]=="Iris-versicolor","Species"]=1
data.loc[data["Species"]=="Iris-virginica","Species"]=2
print(data.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0


In [30]:

data=data.iloc[np.random.permutation(len(data))]
print(data.head())

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
133  134            6.3           2.8            5.1           1.5        2
110  111            6.5           3.2            5.1           2.0        2
10    11            5.4           3.7            1.5           0.2        0
126  127            6.2           2.8            4.8           1.8        2
78    79            6.0           2.9            4.5           1.5        1


# CONVERTING DATASET

In [31]:
X=data.iloc[:,1:5].values
y=data.iloc[:,5].values

print("Shape of X",X.shape)
print("Shape of y",y.shape)
print("Examples of X\n",X[:3])
print("Examples of y\n",y[:3])

Shape of X (150, 4)
Shape of y (150,)
Examples of X
 [[6.3 2.8 5.1 1.5]
 [6.5 3.2 5.1 2. ]
 [5.4 3.7 1.5 0.2]]
Examples of y
 [2 2 0]


# NORMALIZATION

In [33]:
X_normalized=normalize(X,axis=0)
print("Examples of X_normalised\n",X_normalized[:3])

Examples of X_normalised
 [[0.08716562 0.07412052 0.10034783 0.08627246]
 [0.08993278 0.08470916 0.10034783 0.11502995]
 [0.07471338 0.09794497 0.02951407 0.01150299]]


# TRAINING AND TESTING

In [34]:
total_length=len(data)
train_length=int(0.8*total_length)
test_length=int(0.2*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]

print("Length of train set x:",X_train.shape[0],"y:",y_train.shape[0])
print("Length of test set x:",X_test.shape[0],"y:",y_test.shape[0])

Length of train set x: 120 y: 120
Length of test set x: 30 y: 30


# NEURAL NETWORK

In [36]:
from keras.models import Sequential 
from keras.layers import Dense,Activation,Dropout 
from keras.layers.normalization import BatchNormalization 
from keras.utils import np_utils

In [37]:
y_train=np_utils.to_categorical(y_train,num_classes=3)
y_test=np_utils.to_categorical(y_test,num_classes=3)
print("Shape of y_train",y_train.shape)
print("Shape of y_test",y_test.shape)

Shape of y_train (120, 3)
Shape of y_test (30, 3)


In [38]:
model=Sequential()
model.add(Dense(1000,input_dim=4,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(300,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [39]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=20,epochs=10,verbose=1)


Train on 120 samples, validate on 30 samples
Epoch 1/10
120/120 [==============================] - 1s 8ms/step - loss: 1.0902 - acc: 0.2667 - val_loss: 1.0659 - val_acc: 0.6333
Epoch 2/10
120/120 [==============================] - 0s 786us/step - loss: 1.0371 - acc: 0.7250 - val_loss: 0.9848 - val_acc: 0.8333
Epoch 3/10
120/120 [==============================] - 0s 818us/step - loss: 0.9289 - acc: 0.7250 - val_loss: 0.8212 - val_acc: 0.7333
Epoch 4/10
120/120 [==============================] - 0s 768us/step - loss: 0.7491 - acc: 0.8167 - val_loss: 0.5997 - val_acc: 0.7333
Epoch 5/10
120/120 [==============================] - 0s 769us/step - loss: 0.5462 - acc: 0.8000 - val_loss: 0.4009 - val_acc: 0.9667
Epoch 6/10
120/120 [==============================] - 0s 758us/step - loss: 0.3954 - acc: 0.9500 - val_loss: 0.2985 - val_acc: 0.9667
Epoch 7/10
120/120 [==============================] - 0s 813us/step - loss: 0.2785 - acc: 0.9500 - val_loss: 0.1941 - val_acc: 0.9667
Epoch 8/10
120/120 

In [40]:
prediction=model.predict(X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)

accuracy=np.sum(y_label==predict_label)/length * 100 
print("Accuracy of the dataset",accuracy )

Accuracy of the dataset 93.33333333333333
